// Generated by CoffeeScript 1.8.0
$(document).ready(function() {
  var ref;
  ref = new Firebase("https://browse-together.firebaseio.com");
  return chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
    switch (request.type) {
      case 'auth-status':
        return ref.onAuth(function(authData) {
          var main_auth_data;
          main_auth_data = authData;
          return sendResponse(authData);
        });
      case 'google-oauth':
        return ref.authWithOAuthRedirect('google', function(error, authData) {
          return sendResponse(authData);
        });
      case 'github-oauth':
        return ref.authWithOAuthRedirect('github', function(error, authData) {
          return sendResponse(authData);
        });
    }
  });
});
