// Generated by CoffeeScript 1.8.0
var ref;

ref = new Firebase("https://browse-together.firebaseio.com");

chrome.runtime.onMessage.addListener(function(request, sender, sendResponse) {
  switch (request.type) {
    case 'auth-status':
      return ref.onAuth(function(authData) {
        var main_auth_data;
        main_auth_data = authData;
        return sendResponse(authData);
      });
    case 'google-oauth':
      return ref.authWithOAuthRedirect('google', function(error, authData) {
        return sendResponse(authData);
      });
    case 'github-oauth':
      return ref.authWithOAuthRedirect('github', function(error, authData) {
        return sendResponse(authData);
      });
  }
});

chrome.tabs.onUpdated.addListener(function(tabId, changeInfo, tab) {
  console.log(tabId, changeInfo, tab);
  if (changeInfo.status !== 'complete') {
    return;
  }
  return ref.onAuth(function(authData) {
    if (!authData) {
      return;
    }
    return ref.child("users." + authData.uid + "." + tabId).set({
      highlighted: tab.highlighted,
      icon: tab.favIconUrl,
      title: tab.title,
      url: tab.url
    }, function(e) {
      return console.log(e, '123');
    });
  });
});

chrome.tabs.onRemoved.addListener(function(tabId, changeInfo, tab) {
  return ref.onAuth(function(authData) {
    if (!authData) {
      return;
    }
    return ref.child("users." + authData.uid + "." + tabId).remove();
  });
});

chrome.tabs.onActivated.addListener(function(_arg) {
  var tabId, windowId;
  tabId = _arg.tabId, windowId = _arg.windowId;
  return ref.onAuth(function(authData) {
    if (!authData) {
      return;
    }
    return chrome.tabs.getAllInWindow(windowId, function(arr) {
      return ref.onAuth(function(authData) {
        var h, tab, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = arr.length; _i < _len; _i++) {
          tab = arr[_i];
          h = tab.highlighted;
          _results.push(ref.child("users." + authData.uid + "." + tab.id + ".highlighted").set(h, function(e) {
            return console.log(e, '123');
          }));
        }
        return _results;
      });
    });
  });
});
