// Generated by CoffeeScript 1.8.0
document.addEventListener('DOMContentLoaded', function() {
  chrome.runtime.sendMessage({
    type: 'auth-status'
  }, function(user_info) {
    console.log(user_info);
    return $('body').addClass('login');
  });
  return $('.login > div').on('click', function(e) {
    var $el, auth;
    console.log('inside');
    $el = $(e.currentTarget);
    auth = $el.attr('class');
    return chrome.runtime.sendMessage({
      type: "" + auth + "-oauth"
    }, function(user_info) {
      return console.log(user_info);
    });
  });
});
