// Generated by CoffeeScript 1.8.0
document.addEventListener('DOMContentLoaded', function() {
  return $('.login').on('click', function(e) {
    return window.open('https://jasongornall.github.io/browse-together/', '_blank');
  });
});
